### ISSUE TITLE
Pascal's triangle solution error for n>4

### ISSUE THREAD

**Issue by TapanManu** [geekykant/SDE-Placement-Interview#1]
Hi,
When I executed the solution of pascal's triangle , the output is shown as
![pascal_error](https://user-images.githubusercontent.com/48797926/98562696-55070f00-22d0-11eb-9e7f-97aef20e09bd.png)

The output is not suited for values of n>4.

Thanks

**Comment by geekykant** [comment]
You are right @TapanManu, the logic I had coded was wrong.

- I have updated with your correct code ([Pascals Triangle CPP](https://github.com/TapanManu/cprogs/blob/master/cpp/matrix/pascals.cpp))

Thank you!
